### PR TITLE
Update install.sh

### PR DESCRIPTION
**Pull request by wtmpx**

### CODE REVIEW

**Comment by pzirnik** [comment]
I do like the function approach. But i do not like the .SFSCextractorc handling. If the .SFSCextractorrc does not exist at all we just can create it with good defaults. If it does exist we only should touch it if we add new functionality and then only this new lines should be filled in without touching any old settings that (maybe) have been modified already.

**Review by wtmpx — COMMENTED** [review]
I have added new fun. defaultConfig 
The default SFSC is under users home directory. So, I used $HOME

**Comment by pzirnik** [comment]
`#Let us compaire 
    [[ $(md5sum $CONFIG $NEWCONFIG|cut -f1 -d" " |sort -u |wc -l) -eq 2 ]] && {
      diff -y $CONFIG $NEWCONFIG 
      read -p "The $CONFIG is diffrent than initial version, compaire above 
      output. Should I replace your $CONFIG? (y/N)" 
      [[ "${REPLY,,}" == "y" ]] && { cp -p $NEWCONFIG $CONFIG ;} 
    }`

This is not needed, please keep the original code

`grep "FIX_ARCHIVE_RIGHTS" ~/.SFSCextractorrc || echo -e "\n# fix tar archive rights 1=yes 0=no\nFIX_ARCHIVE_RIGHTS=1\n" >> ~/.SFSCextractorrc`

Your code will overwrite any changes made to .SFSCextractorrc (if user confirms with "y") while the orginal code just add the new option with a good default to configuration file, no need to ask the user anything :-)

**Comment by pzirnik** [comment]
I update the install.sh with your changes and my recommendations :-)

**Pull request closed without merging**
